app/Http/routes.php
<?php

Route::get('/',        'frontController@index');
Route::get('home',     'frontController@index');
Route::get('test',     'frontController@test');
Route::get('login',    'frontController@login');
Route::get('app',    'frontController@homeApp');
Route::get('registro', 'frontController@registro');
Route::get('logout', 'LogController@logout');

Route::get('vehiculo/{imei}/ubicacion', ['as' => 'vehiculo.ubicacion', 'uses' => 'carController@ubicacion']);
//Route::get('ubicaciones', 'carController@ubicacion');
Route::get('vehiculo/{id}/historial', ['as' => 'vehiculo.historial', 'uses' => 'carController@historial']);

Route::get('ubicacion/{id}/show', ['as' => 'ubicacion.show', 'uses' => 'LocController@show']);

Route::get('estadisticas', ['as' => 'estadisticas', 'uses' => 'carController@estadisticas']);

Route::resource('vehiculo', 'carController');
Route::resource('usuario', 'userController');
Route::resource('log', 'LogController');
Route::resource('ubica', 'LocController');

app/Car.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Car extends Model {

  protected $table = 'cars';
  protected $fillable = [
    'imei', 
    'telefono',
    'marca',
    'modelo',
    'placa',
    'color',
    'estado',
    'lim_velocidad',
    'user_id',
  ];

}

app/Http/Controllers/carController.php
<?php namespace App\Http\Controllers;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Car;
use App\User;
use App\Location;

use Illuminate\Http\Request;
use Session;
use Redirect;
use Auth;
use DB;


class carController extends Controller {
	public $title = "Trackr";
	public $descr = "Sistema de trackeo";

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		//$vehiculos = Car::All();
		$user 	   = Auth::user()->id;
		$vehiculos = DB::table('cars')->where('user_id',$user)->get();
		return view('car.index', [
	    'title' => $this->title." | Vehiculos",
	    'desc'  => $this->descr,
	    'slug'  => "car.index",
	  ], compact('vehiculos'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		return view('car.create', [
			'title' => $this->title." | Agregar vehiculo",
			'desc'  => $this->descr,
			'slug'  => "car.create"
			]);
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store(Request $request)
	{
		Car::create([
			'imei'          => $request['imei'], 
	    	'telefono'      => $request['telefono'],
	    	'marca'         => $request['marca'],
	    	'modelo'        => $request['modelo'],
	    	'placa'         => $request['placa'],
	    	'color'         => $request['color'],
	    	'estado'        => 'Encendido',
	    	'lim_velocidad' => $request['lim_velocidad'],
	    	'user_id' 		=> Auth::user()->id
		]);
		return redirect('/vehiculo')->with('message', 'store');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		//
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$vehiculo = Car::find($id);
		return view('car.edit', [
			'title' => $this->title." | Agregar vehiculo",
			'desc'  => $this->descr,
			'slug'  => "car.create",
			'car'   => $vehiculo
			]);
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id, Request $request)
	{
		$vehiculo = Car::find($id);
		$vehiculo->fill($request->all());
		$vehiculo->save();
		
		Session::flash('message', 'Vehiculo actualizado con exito');
		return Redirect::to('/vehiculo');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		Car::destroy($id);
		Session::flash('message', 'Vehiculo eliminado con exito');
		return Redirect::to('/vehiculo');
	}


	public function ubicacion($imei)
	{
		$vehiculo = DB::table('locations')->where('imei_car',$imei)->get();
		//return $vehiculo;
		return view('car.ubicaciones', [
			'title' => $this->title." | Ubicacion de vehiculo",
			'desc'  => $this->descr,
			'slug'  => "car.ubicaciones",
			'car'   => $vehiculo
			],compact('vehiculo','imei'));
	}

	public function historial($id)
	{	
		$vehiculo = Car::find($id);
		return view('car.historial', [
			'title' => $this->title." | Historial de ubicaciones de vehiculo",
			'desc'  => $this->descr,
			'slug'  => "car.historial",
			'car'   => $vehiculo
			]);
	}

	public function estadisticas()
	{	
		$user     = Auth::user()->id;
		$cars = DB::table('cars')->where('user_id',$user)->get();
			return view('estadisticas', [
		    'title' => $this->title." | Estadisticas",
		    'desc'  => $this->descr,
		    'slug'  => "estadisticas",
		  ], compact('cars'));		
		
		/*foreach ($vehiculos as $vehi ) {
			$cars 	  = DB::table('locations')->where('imei_car',$vehi->imei)->get();
			return view('estadisticas', [
		    'title' => $this->title." | Estadisticas",
		    'desc'  => $this->descr,
		    'slug'  => "estadisticas",
		  ], compact('cars','vehi'));
		}*/
	}

}

resources/views/car/create.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
<div class="page-wrap has-header">
    
  <!-- LOGIN FORM --> 
  <div class="container form-registro">
    <h1>Agregar vehiculo</h1>
    <hr class="full left">

    {!!Form::open([
      'route'  => 'vehiculo.store',
      'method' => 'POST',
      'class'  => 'form-horizontal'
    ])!!}

    @include('car.form')
    <div class="form-group text-center">
      <div class="col-sm-offset-2 col-sm-10">
        {!!Form::submit('Aceptar',['class' => 'btn btn-primary'])!!}
        {!!Form::reset('Cancelar',['class' => 'btn btn-warning'])!!}
      </div>
    </div>
    
    {!!Form::close()!!}
  </div>
  <!-- LOGIN FORM -->

</div>
@stop
   

resources/views/car/edit.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
<div class="page-wrap has-header">
    
  <!-- LOGIN FORM --> 
  <div class="container form-registro">
    <h1>Editar vehiculo</h1>
    <hr class="full left">

    {!!Form::model($car, [
      'route'  => ['vehiculo.update', $car->id],
      'method' => 'PUT',
      'class'  => 'form-horizontal'
    ])!!}

      @include('car.form')
      <div class="form-group text-center">
        <div class="col-sm-offset-2 col-sm-10">
          {!!Form::submit('Aceptar',['class' => 'btn btn-primary'])!!}
          {!!Form::reset('Cancelar',['class' => 'btn btn-warning'])!!}
        </div>
      </div>
    {!!Form::close()!!}

    {!!Form::open([
      'route'  => ['vehiculo.destroy', $car->id],
      'method' => 'DELETE',
      'class'  => 'form-horizontal'
    ])!!}
      <div class="form-group text-center">
        <div class="col-sm-offset-2 col-sm-10">
          {!!Form::submit('Eliminar',['class' => 'btn btn-danger'])!!}
        </div>
      </div>
    {!!Form::close()!!}
  </div>
  <!-- LOGIN FORM -->

</div>
@stop
   

resources/views/car/estadisticas.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
	<div class="page-wrap has-header">
    
    <div class="container">
      <h1 class="text-center">Estadisticas</h1>
      <hr>

      @foreach($cars as $car)
      <div class="panel panel-default">
        <div class="panel-heading">{{$car->marca}} // {{$car->modelo}} // {{$car->placa}}</div>
        <div class="panel-body">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Velocidad promedio:</th>
                <th>Distancia recorrida:</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td> {{$car->marca} km/h</td>
                <td>km</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      @endforeach

    </div>
  </div>
@stop
    

resources/views/car/form.blade.php
<div class="form-group">
  {!!Form::label('imei', 'IMEI', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('imei',null ,['class' => 'form-control', 'placeholder' => "Introduzca IMEI del dispositivo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('telefono', 'Telefono', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('telefono',null ,['class' => 'form-control', 'placeholder' => "Introduzca linea telefonica del dispositivo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('marca', 'Marca', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('marca',null ,['class' => 'form-control', 'placeholder' => "Introduzca la marca del vehiculo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('modelo', 'Modelo', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('modelo',null ,['class' => 'form-control', 'placeholder' => "Introduzca el modelo del vehiculo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('placa', 'Placa', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('placa',null ,['class' => 'form-control', 'placeholder' => "Introduzca la placa del vehiculo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('color', 'Color', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('color',null ,['class' => 'form-control', 'placeholder' => "Introduzca el color del vehiculo", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  {!!Form::label('lim_velocidad', 'Limite de velocidad', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('lim_velocidad',null ,['class' => 'form-control', 'placeholder' => "Introduzca el limite de velocidad", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

<div class="form-group">
  <label for="input_map" class="control-label col-sm-2">Restriccion de localidad</label>
  <div class="col-sm-10">
    <div id="input_map" name="input_map" class="form-control form-map"></div>
  </div>
</div>

<div class="form-group">
  {!!Form::label('lim_velocidad', 'Limite de velocidad', ["class" => "control-label col-sm-2"])!!}
  <div class="col-sm-10">
    {!!Form::text('lim_velocidad',null ,['class' => 'form-control', 'placeholder' => "Introduzca el limite de velocidad", 'required' => '', 'autofocus' => ''])!!}
  </div>
</div>

resources/views/car/historial.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
	<div class="page-wrap has-header">
    
    <div class="container">
      <h1 class="text-center">Historial de ubicaciones</h1>
      <p class="text-center"> {{$car->marca}} // {{$car->modelo}} // {{$car->placa}} </p>
      <hr>

      <div class="panel panel-default">
        <div class="panel-heading">Fecha</div>
        <div class="panel-body">
          <table class="table table-striped table-hover">
            <thead>
              <tr>
                <th>Direccion</th>
                <th>Hora</th>
                <th>Velocidad</th>
                <th>Distancia</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>
@stop
    

resources/views/car/index.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)


@section('content')
<div class="page-wrap has-header">
  <div class="container">
    <h1 class="text-center">Vehiculos</h1>
    <hr>  

    <!-- MENSAJE -->
    @if( Session::has('message'))
      <div class="alert alert-success alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ Session::get('message')}}
      </div>
    @endif
    <!-- MENSAJE -->

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>IMEI</th>
          <th>Marca</th>
          <th>Modelo</th>
          <th>Placa</th>
          <th><i class="glyphicon glyphicon-option-horizontal"></i></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
          <td>
              {!! link_to_route('vehiculo.create', 'Agregar nuevo vehiculo',null, ['class' => 'btn btn-default btn-sm btn-primary'])!!}
          </td>
        </tr>
      @foreach($vehiculos as $car)
        <tr>
          <td>{{$car->imei}}</td>
          <td>{{$car->marca}}</td>
          <td>{{$car->modelo}}</td>
          <td>{{$car->placa}}</td>
          <td class="shrink">
            {!! link_to_route('vehiculo.ubicacion', 'Ver Ubicacion', $car->imei, ['class' => 'btn btn-default btn-sm btn-primary'])!!}
            {!! link_to_route('vehiculo.historial', 'Ver Historial', $car->id, ['class' => 'btn btn-default btn-sm btn-success'])!!}
            {!! link_to_route('vehiculo.edit', 'Editar Vehiculo', $car->id, ['class' => 'btn btn-default btn-sm btn-warning'])!!}
          </td>
        </tr>
      @endforeach
      </tbody>
    </table>
  </div>    

</div>
@stop
   

resources/views/car/ubicacion.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)

@section('content')
	<div class="has-header"></div>
	<div class="testMap-container">
        <div id="testMap"></div>
        <div class="distance">
         	Distancia total recorrida:
         	<span>0</span>Km
         </div>
    </div>
@stop
    

resources/views/car/ubicaciones.blade.php
@extends('layouts.base-loged')

@section('title', $title)
@section('desc', $desc)


@section('content')
<div class="page-wrap has-header">
  <div class="container">
    <h1 class="text-center">Ubicaciones "{{$imei}}"</h1>
    <hr>  

    <!-- MENSAJE -->
    @if( Session::has('message'))
      <div class="alert alert-success alert-dismissible text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        {{ Session::get('message')}}
      </div>
    @endif
    <!-- MENSAJE -->

    <table class="table table-striped table-hover">
      <thead>
        <tr>
          <th>IMEI</th>
          <th>Longitud</th>
          <th>Latitud</th>
          <th>Direccion</th>
          <th>Fecha y Hora</th>
          <th>velocidad</th>
          <th>distancia</th>
          <th><i class="glyphicon glyphicon-option-horizontal"></i></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td></td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      @foreach($vehiculo as $car)
        <tr>
          <td>{{$car->imei_car}}</td>
          <td>{{$car->longitud}}</td>
          <td>{{$car->latitud}}</td>
          <td>{{$car->direccion}}</td>
          <td>{{$car->fecha_hora}}</td>
          <td>{{$car->velocidad}}</td>
          <td>{{$car->distancia}}</td>
        </tr>
      @endforeach
      </tbody>
    </table>
  </div>    

</div>
@stop
   